# FROM sonarqube:8.9-community
FROM mc1arke/sonarqube-with-community-branch-plugin:lts

COPY sonarqube-community-branch-plugin-1.8.0.jar /opt/sonarqube/extensions/plugins


# docker run -d --name sonarqube -p 9000:9000 sonarqube:7.5-community
# docker create sonarqube-custom


# docker build --tag=sonarqube-custom .
# docker create -p 9000:9000 sonarqube-custom


# docker build --tag=sonarqube-plugin 
# docker create -p 9000:9000 sonarqube-plugin

----- begin xxxx-----
SHA256:ePkg5icWzNqQkcD3BD1JZnnGCrF4oTqOZPF9yLNURD4=
----- end xxx-----